language: node_js
node_js:
  - "node"
install:
  - npm install
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE be_inquantifiable_selves_express_test; \c be_inquantifiable_selves_express_test; CREATE EXTENSION citext;' -U postgres
  - 

# create db
# add citext
# CREATE EXTENSION citext;
