language: node_js
node_js:
  - "node"
install:
  - npm install
services:
  - postgresql
before_script:
  # - psql -c 'CREATE DATABASE be_inquantifiable_selves_express_test;' -U postgres
  # - psql -c '\c be_inquantifiable_selves_express_test;'
  # - psql -c 'CREATE EXTENSION citext;'

# create db
# add citext
# CREATE EXTENSION citext;
